config/routes.rb
Rails.application.routes.draw do
  root to: 'index#index'

  get :form_redirect, controller: :application
  get :flash_message, controller: :application
  get :"terms-of-service", controller: :static_pages
  get :"privacy-policy", controller: :static_pages
  get :faq, controller: :static_pages
  get :donate, controller: :static_pages
  post :donate, controller: :static_pages, action: :one_time_donation
  get :emoji, controller: :static_pages
  get :chat, controller: :chat
  get :chat_list, controller: :chat
  get "chat/remove_message/:id" => "chat#remove_message", as: :remove_message
  get "chat/revoke_access/:id" => "chat#revoke_access", as: :revoke_access

  resource :feedback, path: "feedback", only: [:show, :create] do
    get ":id/edit", action: :edit, as: :edit
    post ":id/complete", action: :complete, as: :complete
    get :all, action: :index
    post :all, action: :redirect_all
  end

  devise_for :users, path: :account, path_names: { sign_in: "login", sign_out: "logout" }, controllers: {
    confirmations: "devise/user/confirmations",
    # omniauth_callbacks: "devise/user/omniauth_callbacks",
    passwords: "devise/user/passwords",
    registrations: "devise/user/registrations",
    sessions: "devise/user/sessions",
    unlocks: "devise/user/unlocks"
  }

  get "tags/:tags" => "tags#show", as: :tag
  resources :tags, only: [ :index ] do
    post :redirect, on: :collection
  end

  post "history" => "posts#history_redirect", as: :history_redirect
  get "history(((((/:claimed_status)/:reply_count)/:user_status)/:tags)/:page)" => "posts#history", as: :history

  get "url" => "replies#meta", as: :get_meta
  get "preview" => "replies#preview"
  get "posts/:id.csv" => "posts#show", format: :csv
  resources :posts, except: [ :destroy ] do
    member do
      get :vote
      get :subscribe
      post :mod
    end
    resources :replies, only: [ :create, :update ] do
      post :mod
      get :favorite
      get :unfavorite
    end
  end

  resources :replies, only: [ :index ] do
  end

  resource :mod, only: [:show] do
    get :queue, on: :member

    resource :bans, only: [:show] do
      resources :banned_users, path: :users
      resources :banned_ips, path: :ip
      resources :chat_bans, path: :chat
    end
    resources :audit, only: [ :index, :show ] do
      post :search, on: :collection
    end
  end

  resource :admin, only: [] do
    resources :email_blobs, path: :emails do
      post :search, on: :collection
    end
  end

  resource :account, only: [ :index, :edit, :update ] do
    get :confirm
    patch :confirm, action: :set_confirmation
    get :avatar
    post :avatar, action: :update_avatar
    get :notifications

    resources :subscriptions, only: [ :index ] do
      collection do
        post :subscribe
        delete :subscribe, action: :unsubscribe
      end
    end
    resources :friends, only: [ :index, :update, :destroy ]
    resources :profile, only: [ :index ] do
      post :update, on: :collection
    end
    resources :settings, only: [ :index ] do
      post :update, on: :collection
    end
    resources :notices, only: [ :index ] do
      post :mark_all_read, on: :collection
    end
    resources :invites, only: [ :index ] do
      post :mark_all_read, on: :collection
    end
  end

  post "update_user_search" => "users#update_user_search", as: :update_user_search
  resources :users, except: [ :destroy ] do
    member do
      put :add_friend
      put :remove_friend
      post :moderate
      get :spy
    end
    get "shoutbox" => "shouts#index", as: :shouts
    post "shoutbox" => "shouts#create"
    get "shout-trail/:other_user_id" => "shouts#shouttrail", as: :shouttrail
    resources :posts, only: [ :index ]
    resources :replies, only: [ :index ]
  end
  resources :shouts, only: [:show, :update, :destroy]

  resources :webhooks, only: [] do
    collection do
      post :email
    end
  end

  require 'sidekiq/web'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount ActionCable.server => '/cable'

end

app/models/shout.rb
# == Schema Information
#
# Table name: shouts
#
#  id           :integer          not null, primary key
#  sent_from_id :integer
#  sent_to_id   :integer
#  body         :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  read_at      :datetime
#  removed_at   :datetime
#

class Shout < ApplicationRecord
  include Readable
  include UrlHelper
  include Sherlockable

  sherlockable klass: :shout, ignore: [ :created_at, :updated_at, :read_at ]

  belongs_to :sent_from, class_name: "User"
  belongs_to :sent_to,   class_name: "User"

  scope :between, ->(user1, user2) { where("(sent_from_id = :user1 AND sent_to_id = :user2) OR (sent_from_id = :user2 AND sent_to_id = :user1)", user1: user1, user2: user2) }
  scope :not_banned, -> { joins(:sent_from).where("users.banned_until IS NULL OR users.banned_until < ?", DateTime.current) }
  scope :not_removed, -> { where(shouts: { removed_at: nil }) }
  scope :displayable, -> { not_banned unless Rails.env.archive? }

  after_commit :broadcast_creation, :notify_user

  validate :valid_text

  def removed?; removed_at?; end

  def restore=(val)
    self.removed_at = nil if val.to_s.downcase == "true"
  end

  private

  def valid_text
    if body.to_s.length == 0
      errors.add(:base, "Try adding some more text! This isn't long enough.")
    end
  end

  def shouts_path
    Rails.application.routes.url_helpers.user_shouts_path(sent_to_id, anchor: "shout-#{id}")
  end

  def notify_user
    return unless updated_at == created_at
    return unless sent_to.settings.send_reply_notifications?
    return if sent_to.banned?

    NotificationsWorker.perform_in(1.minute, sent_to_id)
  end

  def broadcast_creation
    if updated_at == created_at
      ActionCable.server.broadcast("notifications_#{sent_to_id}", message: "New Shout from <a href=\"#{shouts_path}\">#{sent_from.username}</a>".html_safe)
    else
      ActionCable.server.broadcast("notifications_#{sent_to_id}", {})
    end
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  before_action :authenticate_mod, only: [:show]

  def show
    shout = Shout.find(params[:id])
    redirect_to user_shouttrail_path(shout.sent_from, shout.sent_to, shout_id: params[:id], anchor: "shout-#{shout.id}")
  end

  def index
    @user = User.find(params[:user_id])
    @shouts = @user.shouts_to.displayable.order(created_at: :desc, id: :desc).first(50)
    @shouts_from = User.not_banned.joins(:shouts_from)
      .where(shouts: { sent_to_id: @user.id })
      .group("users.id")
      .order("MAX(shouts.created_at) DESC")
      .limit(50)

    if @user == current_user
      @user.shouts.unread.each(&:read)
    end
  end

  def shouttrail
    @user = User.find(params[:user_id])
    @other_user = User.find(params[:other_user_id])
    @user, @other_user = @other_user, @user if @other_user == current_user
    find_shouts

    if @user == current_user
      @user.shouts_to.unread.where(sent_from_id: @other_user.id).each(&:read)
    elsif @other_user == current_user
      @other_user.shouts_to.unread.where(sent_from_id: @user.id).each(&:read)
    end
  end

  def create
    @user = User.find(params[:user_id])
    @shout = @user.shouts_to.create(body: params[:shout][:body], sent_from_id: current_user.id)

    if @shout.persisted?
      redirect_to user_shouttrail_path(current_user, @user)
    else
      redirect_to user_shouttrail_path(current_user, @user), alert: "No matter how loud you shout it, nobody will hear if you say nothing."
    end
  end

  def update
    @shout = Shout.find(params[:id])
    return redirect_back(fallback_location: user_shouts_path(@shout.sent_to)) unless current_mod? || current_user == @shout.sent_from

    @shout.update(shout_params)
    redirect_to user_shouttrail_path(@shout.sent_from, @shout.sent_to)
  end

  def destroy
    shout = Shout.find(params[:id])
    shout.update(removed_at: DateTime.current)
    redirect_back fallback_location: user_shouts_path(shout.sent_to)
  end

  private

  def shout_params
    params.require(:shout).permit(:restore, :body)
  end

  def find_shouts
    if params[:shout_id]
      limit = 100
      shout_ids = Shout.between(@user, @other_user).order(created_at: :desc, id: :desc).pluck(:id)
      shout_idx = shout_ids.index(params[:shout_id].to_i)
      min_idx = [shout_idx - (limit / 2), 0].max
      max_idx = [shout_idx + (limit / 2), shout_ids.length - 1].min
      focused_shout_ids = shout_ids[min_idx..max_idx]
      @shouts = Shout.includes(:sent_from, :sent_to).where(id: focused_shout_ids).order(created_at: :desc, id: :desc)
    else
      @shouts = Shout.displayable.includes(:sent_from, :sent_to).between(@user, @other_user).order(created_at: :desc, id: :desc).first(50)
    end
  end

end

app/views/shouts/_index.html.erb
<% hide_shouttrail ||= false %>
<% shouts.each do |shout| %>
  <% if shout.removed? %>
    <div class="removed-shout <%= 'clickable' if current_mod? %>">Shout removed</div>
    <% unless current_mod? %>
      <hr><% next %>
    <% end %>
  <% end %>
  <% shouter = shout.sent_from %>
  <% shoutee = shout.sent_to %>
  <div class="shout-container <%= 'removed hidden' if shout.removed? %>" id="shout-<%= shout.id %>">
    <div class="shout-author">
      <%= avatar(shouter.avatar(size: 30), size: 30) %>
      <div class="author-details">
        <div class="author-name">
          <a href="<%= user_shouts_path(shouter) %>"><%= shouter.username %></a>
        </div>
        <div class="timestamp">
          <%= timeago(shout.created_at) %>
          <% unless hide_shouttrail %>
            - <a href="<%= user_shouttrail_path(@user, shouter) %>">Shouttrail</a>
          <% end %>
        </div>
      </div>
      <div class="report-flag">
        <% if shout.removed? %>
          <%= hover_icon(:bin_t, "Restore Shout", href: shout_path(shout, shout: {restore: true}), method: :patch) if can?(:remove_shouts) %>
        <% else %>
          <% if can?(:remove_shouts) || shouter == current_user %>
            <%= hover_icon(:bin, "Remove Shout", href: shout_path(shout), method: :delete, data: { confirm: "Are you sure you want to remove this shout?" }) %>
            <%= hover_icon(:comment_edit, "Edit Shout", class: "edit-shout") %>
          <% else %>
            <%= hover_icon(:flag_red, "Report this shout to Moderators", href: feedback_path(report_url: user_shouts_url(shoutee, anchor: "shout-#{shout.id}"))) %>
          <% end %>
        <% end %>
      </div>
    </div>
    <% if can?(:remove_shouts) || shouter == current_user %>
      <div class="shout-edit hidden">
        <%= form_for shout do |f| %>
          <div class="text-area-wrapper">
            <%= render partial: "layouts/markdown_tools" %>
            <%= f.text_area :body, rows: 8, class: "autofillable-field" %>
          </div>
          <div class="text-right">
            <%= f.submit "Reshout!" %>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="shout-body">
      <% markdown_opts = {} %>
      <% markdown_opts[:except] = [:whisper_reveal] unless current_mod? || current_user == shoutee || current_user == shouter %>
      <%= markdown(posted_by_user: shouter, **markdown_opts) { shout.body } %>
    </div>
  </div>
  <hr>
<% end %>

app/views/shouts/index.html.erb
<% meta_title "#{@user.username}'s ShoutBox • Help-QA.com" %>

<div class="shout-title">
  <i>Shoutbox: </i> <a href="<%= user_path(@user) %>" class="underline"><%= @user.username %></a> is listening
  <p>Just a simple "Hello", "Thanks", or chat! <a href="<%= user_path(@user) %>" class="underline">Back to <%= @user.username %>'s profile...</a></p>
  <hr>
</div>

<div class="shout-wrapper">
  <div class="shout-list">
    <%= render partial: "index", locals: { shouts: @shouts } %>
  </div>
  <div class="new-shout">
    <% if user_signed_in? %>
      <% if @user == current_user %>
        <p>You're welcome to leave a shout for yourself... But you'll have to provide both sides of the conversation!</p>
      <% else %>
        <p>Leave a shout for <%= @user.username %></p>
      <% end %>
      <%= form_for [@user, Shout.new] do |f| %>
        <div class="text-area-wrapper">
          <%= render partial: "layouts/markdown_tools" %>
          <%= f.text_area :body, rows: 8, class: "autofillable-field" %>
        </div>
        <div class="text-right">
          <%= f.submit "Shout!" %>
          <% if @user == current_user %>
            (Shouting yourself)
          <% end %>
        </div>
      <% end %>
    <% else %>
      <p>You must be signed in to leave shouts for Helpers</p>
    <% end %>
    <div class="shout-users">
      <div class="title">Shouts From:</div>
      <% @shouts_from.each do |shouter| %>
        <%= avatar(shouter.avatar(size: 65), size: 65, href: user_path(shouter), title: shouter.username) %>
      <% end %>
    </div>
  </div>
</div>

app/views/shouts/shouttrail.html.erb
<% meta_title "#{@user.username}'s ShoutTrail with #{@other_user.username} • Help-QA.com" %>

<div class="shout-title">
  <i>ShoutTrail: </i> <a href="<%= user_shouts_path(@user) %>" class="underline"><%= @user.username %></a> and <a href="<%= user_shouts_path(@other_user) %>" class="underline"><%= @other_user.username %></a>
  <p>Just a simple "Hello", "Thanks", or chat! <a href="<%= user_path(@other_user) %>" class="underline">Back to <%= @other_user.username %>'s profile...</a></p>
  <hr>
</div>

<div class="shout-wrapper">
  <div class="shout-list">
    <%= render partial: "index", locals: { shouts: @shouts, hide_shouttrail: true } %>
  </div>
  <div class="new-shout">
    <% if user_signed_in? %>
      <% if @user == current_user %>
        <p>Leave a shout for <%= @other_user.username %></p>
        <%= form_for [@other_user, Shout.new] do |f| %>
          <div class="text-area-wrapper">
            <%= render partial: "layouts/markdown_tools" %>
            <%= f.text_area :body, rows: 8, class: "autofillable-field" %>
          </div>
          <div class="text-right">
            <%= f.submit "Shout!" %>
            <% if @other_user == current_user %>
              (Shouting yourself)
            <% end %>
          </div>
        <% end %>
      <% else %>
        <p>This shout trail doesn't involve you. Visit the shoutbox of either user to leave a shout for them!</p>
      <% end %>
    <% else %>
      <p>You must be signed in to leave shouts for Helpers</p>
    <% end %>
  </div>
</div>