config/routes.rb
Rails.application.routes.draw do
  root to: 'index#index'

  get :form_redirect, controller: :application
  get :flash_message, controller: :application
  get :"terms-of-service", controller: :static_pages
  get :"privacy-policy", controller: :static_pages
  get :faq, controller: :static_pages
  get :donate, controller: :static_pages
  post :donate, controller: :static_pages, action: :one_time_donation
  get :emoji, controller: :static_pages
  get :chat, controller: :chat
  get :chat_list, controller: :chat
  get "chat/remove_message/:id" => "chat#remove_message", as: :remove_message
  get "chat/revoke_access/:id" => "chat#revoke_access", as: :revoke_access

  resource :feedback, path: "feedback", only: [:show, :create] do
    get ":id/edit", action: :edit, as: :edit
    post ":id/complete", action: :complete, as: :complete
    get :all, action: :index
    post :all, action: :redirect_all
  end

  devise_for :users, path: :account, path_names: { sign_in: "login", sign_out: "logout" }, controllers: {
    confirmations: "devise/user/confirmations",
    # omniauth_callbacks: "devise/user/omniauth_callbacks",
    passwords: "devise/user/passwords",
    registrations: "devise/user/registrations",
    sessions: "devise/user/sessions",
    unlocks: "devise/user/unlocks"
  }

  get "tags/:tags" => "tags#show", as: :tag
  resources :tags, only: [ :index ] do
    post :redirect, on: :collection
  end

  post "history" => "posts#history_redirect", as: :history_redirect
  get "history(((((/:claimed_status)/:reply_count)/:user_status)/:tags)/:page)" => "posts#history", as: :history

  get "url" => "replies#meta", as: :get_meta
  get "preview" => "replies#preview"
  get "posts/:id.csv" => "posts#show", format: :csv
  resources :posts, except: [ :destroy ] do
    member do
      get :vote
      get :subscribe
      post :mod
    end
    resources :replies, only: [ :create, :update ] do
      post :mod
      get :favorite
      get :unfavorite
    end
  end

  resources :replies, only: [ :index ] do
  end

  resource :mod, only: [:show] do
    get :queue, on: :member

    resource :bans, only: [:show] do
      resources :banned_users, path: :users
      resources :banned_ips, path: :ip
      resources :chat_bans, path: :chat
    end
    resources :audit, only: [ :index, :show ] do
      post :search, on: :collection
    end
  end

  resource :admin, only: [] do
    resources :email_blobs, path: :emails do
      post :search, on: :collection
    end
  end

  resource :account, only: [ :index, :edit, :update ] do
    get :confirm
    patch :confirm, action: :set_confirmation
    get :avatar
    post :avatar, action: :update_avatar
    get :notifications

    resources :subscriptions, only: [ :index ] do
      collection do
        post :subscribe
        delete :subscribe, action: :unsubscribe
      end
    end
    resources :friends, only: [ :index, :update, :destroy ]
    resources :profile, only: [ :index ] do
      post :update, on: :collection
    end
    resources :settings, only: [ :index ] do
      post :update, on: :collection
    end
    resources :notices, only: [ :index ] do
      post :mark_all_read, on: :collection
    end
    resources :invites, only: [ :index ] do
      post :mark_all_read, on: :collection
    end
  end

  post "update_user_search" => "users#update_user_search", as: :update_user_search
  resources :users, except: [ :destroy ] do
    member do
      put :add_friend
      put :remove_friend
      post :moderate
      get :spy
    end
    get "shoutbox" => "shouts#index", as: :shouts
    post "shoutbox" => "shouts#create"
    get "shout-trail/:other_user_id" => "shouts#shouttrail", as: :shouttrail
    resources :posts, only: [ :index ]
    resources :replies, only: [ :index ]
  end
  resources :shouts, only: [:show, :update, :destroy]

  resources :webhooks, only: [] do
    collection do
      post :email
    end
  end

  require 'sidekiq/web'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount ActionCable.server => '/cable'

end

app/controllers/audit_controller.rb
class AuditController < ApplicationController
  include AuditHelper
  helper_method :current_filter
  before_action :authenticate_mod

  def index
    set_audit_filters
  end

  def search
    redirect_to mod_audit_index_path(current_filter)
  end

  def show
    @audit = Sherlock.find(params[:id])
  end

  private

  def current_filter
    @current_filter ||= begin
      params.permit(:ip, :acting_uid, :meta_id, discovery_types: [], discovery_klasses: []).to_h
    end
  end

end

app/helpers/audit_helper.rb
module AuditHelper

  def set_audit_filters
    @audits = Sherlock.order(created_at: :desc).page(params[:page]).per(50)

    discovery_type_filter = current_filter[:discovery_types].to_a.map(&:to_sym)
    @audits = @audits.by_type(*discovery_type_filter) if discovery_type_filter.any?
    dicovery_klass_filter = current_filter[:discovery_klasses].to_a.map(&:to_sym)
    @audits = @audits.by_klass(*dicovery_klass_filter) if dicovery_klass_filter.any?

    @audits = @audits.search_ip(current_filter[:ip].split(",")) if current_filter[:ip].present?
    @audits = @audits.where(acting_user_id: current_filter[:acting_uid].split(",")) if current_filter[:acting_uid].present?

    if current_filter[:meta_id].present?
      queries = []
      current_filter[:meta_id].split(",").each do |search_id|
        klass, meta_id = search_id.include?("-") ? search_id.split("-") : ["", search_id]
        klass_query = if klass.present? && Sherlock.discovery_klasses.include?(klass.to_sym)
          "discovery_klass = '#{klass}'"
        end
        type_query = "obj_id = #{meta_id}"
        queries << "(#{[klass_query, type_query].compact.join(' AND ')})"
      end
      @audits = @audits.where(queries.join(" OR "))
    end
  end
  # TODO?
  # To search for replies for a specific post, select reply checkboxes, but put post-# in the meta
  # (Meta tags should also refer to associated objects, post, user, etc.)

end

app/views/audit/_hash_cell.html.erb
<table class="data-table">
  <% data.each do |data_key, data_val| %>
    <% next unless data_val.present? %>
    <tr>
      <td><%= data_key.titleize %></td>
      <td><%= data_val.to_s.html_safe %></td>
    </tr>
  <% end %>
</table>

app/views/audit/_index.html.erb
<% audits.each do |audit| %>
  <tr>
    <td><a href="<%= mod_audit_path(audit) %>" class="underline"><%= audit.id %></a></td>
    <td>
      <%= audit.created_at.to_formatted_s(:basic) %> <br>
      <small><%= timeago(audit.created_at) %></small>
    </td>
    <td><%= audit.audit_type %></td>
    <td><%= audit.acting_ip.presence || "--" %></td>
    <td><%= audit.acting_user_id.presence || "--" %></td>
    <td><%= audit.obj_id.presence || "--" %> <br> <small><%= audit.obj_klass %></small></td>
  </tr>
<% end %>
<% if audits.none? && !request.xhr? %>
  <p>No audits found</p>
<% end %>

app/views/audit/_object_cell.html.erb
<div class="object-cell">
  <% if @audit.obj.present? %>
    <% case @audit.obj_klass %>
    <% when "User" %>
      User: <%= link_to obj.username, obj %>
    <% when "UserProfile", "UserSetting" %>
      User: <%= link_to obj.user.username, obj.user %>
    <% when "Post" %>
      Post: <%= link_to obj.title, post_path(obj) %>
      <br>
      Author: <%= link_to obj.author.username, obj.author %>
    <% when "Reply" %>
      Author: <%= link_to obj.author.username, obj.author %>
      <br>
      <%= link_to post_path(obj.post_id, anchor: "reply-#{obj.id}") do %>
        Reply:
        <small><%= obj.body %></small>
      <% end %>
    <% when "Shout" %>
      Author: <%= link_to obj.sent_from.username, obj.sent_from %>
      <br>
      <%= link_to user_shouts_path(obj.sent_to_id, anchor: "shout-#{obj.id}") do %>
        Shout:
        <small><%= obj.body %></small>
      <% end %>
    <% when "ChatMessage" %>
      Author: <%= link_to obj.author.username, obj.author %>
      <br>
      <%= link_to chat_url(message: obj.id) do %>
        Message:
        <small><%= obj.body %></small>
      <% end %>
    <% when "BannedIp" %>
      Banned IP Address: <%= obj.ip %>
    <% else "Unknown Class: #{obj_klass}" %>
    <% end %>
  <% else %>
    This <%= @audit.obj_klass %> has been deleted.
  <% end %>
</div>

app/views/audit/index.html.erb
<%= meta_no_index %>
<% total_audits = @audits.total_count || 0 %>
<% first_audit = [(@audits.limit_value * (@audits.current_page - 1)) + 1, total_audits, 0].sort[1] %>
<% last_audit = [@audits.limit_value * @audits.current_page, total_audits, 0].sort[1] %>
<% title = "#{pluralize_with_delimiter(total_audits, 'audit')}, Audits #{number_with_delimiter(first_audit)} to #{number_with_delimiter(last_audit)}" %>
<% meta_title title %>

<h2><i>Audits:</i> <br class="xsmall-down"><%= title %></h2>

<div class="history-page">
  <%= form_tag search_mod_audit_index_path do %>
    <div class="search-form">
      <!-- Time range -->
      <h6>Action Type</h6>
      <div class="split-half">
        <div class="discovery-type">
          <% dicovery_type_filter = current_filter[:discovery_types].to_a.map(&:to_sym) %>
          <% Sherlock.discovery_types.keys.each do |discovery_type| %>
            <%= check_box_tag "discovery_types[]", discovery_type, dicovery_type_filter.include?(discovery_type), id: "discovery_type_#{discovery_type}" %>
            <label for="discovery_type_<%= discovery_type %>"><%= discovery_type %></label>
            <br>
          <% end %>
        </div>
        <div class="discovery-klass">
          <% dicovery_klass_filter = current_filter[:discovery_klasses].to_a.map(&:to_sym) %>
          <% Sherlock.discovery_klasses.each do |discovery_klass| %>
            <%= check_box_tag "discovery_klasses[]", discovery_klass, dicovery_klass_filter.include?(discovery_klass), id: "discovery_klass_#{discovery_klass}" %>
            <label for="discovery_klass_<%= discovery_klass %>"><%= discovery_klass %></label>
            <br>
          <% end %>
        </div>
      </div>
      <h6>IP Address</h6>
      <input type="text" name="ip" value="<%= params[:ip] %>">
      <h6>Acting UID</h6>
      <input type="text" name="acting_uid" value="<%= params[:acting_uid] %>">
      <h6>Meta ID</h6>
      <input type="text" name="meta_id" value="<%= params[:meta_id] %>">
      <%= submit_tag "Search" %>
      <br>
      <small>• "Meta ID" refers to the ID of the object the Audit is tracking. For example, in an edited post, the Meta ID refers to the Post ID.</small>
      <br>
      <small>• In order to specify a specific object id, append the object type with a hyphen before the id. "post-100" to search for all audits related to post with id 100.</small>
      <br>
      <small>• All values can be searched for multiple at once by splitting with commas. ("post-100, user-54")</small>
    </div>
  <% end %>
  <div class="search-results">
    <% total_pages = 5 %>
    <% window_sizes = {
      default: (total_pages / 2).floor,
      low: total_pages - @audits.current_page,
      high: total_pages - (@audits.total_pages - @audits.current_page) - 1
    } %>

    <%= paginate @audits, window: window_sizes.values.max, outer_window: 1, params: current_filter %>
    <table>
      <thead>
        <th>Audit ID</th>
        <th>Date</th>
        <th>Type</th>
        <th>Acting IP</th>
        <th>Acting UID</th>
        <th>Meta ID</th>
      </thead>
      <tbody>
        <%= render partial: "index", locals: { audits: @audits } %>
      </tbody>
    </table>
    <%= paginate @audits, window: window_sizes.values.max, outer_window: 1, params: current_filter %>
  </div>
</div>

app/views/audit/show.html.erb
<%= meta_no_index %>
<h1>Audit #<%= @audit.id %>: <%= @audit.audit_type %></h1>

<table class="audit-table">
  <tr>
    <td>Timestamp</td>
    <td><%= @audit.created_at.to_formatted_s(:basic) %></td>
  </tr>
  <tr>
    <td>Acting Ip</td>
    <td>
      <% if @audit.acting_ip.present? %>
        <%= link_to @audit.acting_ip, mod_audit_index_path(ip: @audit.acting_ip) %>
      <% else %>
        &gt;&gt; Manually edited from Console
      <% end %>
    </td>
  </tr>
  <% if @audit.acting_user_id.present? %>
    <tr>
      <td>Acting User</td>
      <td><%= link_to @audit.acting_user.username, @audit.acting_user %></td>
    </tr>
  <% end %>
  <tr>
    <td>Audited Object</td>
    <td><%= render partial: "object_cell", locals: {obj: @audit.obj} %></td>
  </tr>
  <% changes = @audit.changes %>
  <tr>
    <td>Pre-change Data</td>
    <td class="show-deleted"><%= render partial: "hash_cell", locals: {data: changes[:previous]} %></td>
  </tr>
  <tr>
    <td>Current Data</td>
    <td class="show-added"><%= render partial: "hash_cell", locals: {data: changes[:current]} %></td>
  </tr>
</table>