config/routes.rb
Rails.application.routes.draw do
  root to: 'index#index'

  get :form_redirect, controller: :application
  get :flash_message, controller: :application
  get :"terms-of-service", controller: :static_pages
  get :"privacy-policy", controller: :static_pages
  get :faq, controller: :static_pages
  get :donate, controller: :static_pages
  post :donate, controller: :static_pages, action: :one_time_donation
  get :emoji, controller: :static_pages
  get :chat, controller: :chat
  get :chat_list, controller: :chat
  get "chat/remove_message/:id" => "chat#remove_message", as: :remove_message
  get "chat/revoke_access/:id" => "chat#revoke_access", as: :revoke_access

  resource :feedback, path: "feedback", only: [:show, :create] do
    get ":id/edit", action: :edit, as: :edit
    post ":id/complete", action: :complete, as: :complete
    get :all, action: :index
    post :all, action: :redirect_all
  end

  devise_for :users, path: :account, path_names: { sign_in: "login", sign_out: "logout" }, controllers: {
    confirmations: "devise/user/confirmations",
    # omniauth_callbacks: "devise/user/omniauth_callbacks",
    passwords: "devise/user/passwords",
    registrations: "devise/user/registrations",
    sessions: "devise/user/sessions",
    unlocks: "devise/user/unlocks"
  }

  get "tags/:tags" => "tags#show", as: :tag
  resources :tags, only: [ :index ] do
    post :redirect, on: :collection
  end

  post "history" => "posts#history_redirect", as: :history_redirect
  get "history(((((/:claimed_status)/:reply_count)/:user_status)/:tags)/:page)" => "posts#history", as: :history

  get "url" => "replies#meta", as: :get_meta
  get "preview" => "replies#preview"
  get "posts/:id.csv" => "posts#show", format: :csv
  resources :posts, except: [ :destroy ] do
    member do
      get :vote
      get :subscribe
      post :mod
    end
    resources :replies, only: [ :create, :update ] do
      post :mod
      get :favorite
      get :unfavorite
    end
  end

  resources :replies, only: [ :index ] do
  end

  resource :mod, only: [:show] do
    get :queue, on: :member

    resource :bans, only: [:show] do
      resources :banned_users, path: :users
      resources :banned_ips, path: :ip
      resources :chat_bans, path: :chat
    end
    resources :audit, only: [ :index, :show ] do
      post :search, on: :collection
    end
  end

  resource :admin, only: [] do
    resources :email_blobs, path: :emails do
      post :search, on: :collection
    end
  end

  resource :account, only: [ :index, :edit, :update ] do
    get :confirm
    patch :confirm, action: :set_confirmation
    get :avatar
    post :avatar, action: :update_avatar
    get :notifications

    resources :subscriptions, only: [ :index ] do
      collection do
        post :subscribe
        delete :subscribe, action: :unsubscribe
      end
    end
    resources :friends, only: [ :index, :update, :destroy ]
    resources :profile, only: [ :index ] do
      post :update, on: :collection
    end
    resources :settings, only: [ :index ] do
      post :update, on: :collection
    end
    resources :notices, only: [ :index ] do
      post :mark_all_read, on: :collection
    end
    resources :invites, only: [ :index ] do
      post :mark_all_read, on: :collection
    end
  end

  post "update_user_search" => "users#update_user_search", as: :update_user_search
  resources :users, except: [ :destroy ] do
    member do
      put :add_friend
      put :remove_friend
      post :moderate
      get :spy
    end
    get "shoutbox" => "shouts#index", as: :shouts
    post "shoutbox" => "shouts#create"
    get "shout-trail/:other_user_id" => "shouts#shouttrail", as: :shouttrail
    resources :posts, only: [ :index ]
    resources :replies, only: [ :index ]
  end
  resources :shouts, only: [:show, :update, :destroy]

  resources :webhooks, only: [] do
    collection do
      post :email
    end
  end

  require 'sidekiq/web'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount ActionCable.server => '/cable'

end

app/views/index/index.html.erb
<% if !user_signed_in? %>
  <%= content_for(:head_scripts) do %>
    <script src="https://www.google.com/recaptcha/api.js"></script>
  <% end %>
<% end %>

<div class="front-page">
  <div class="users-side">
    <div class="wrapper">
      <div class="intro">
        <h6>Change Your World</h6>
        <p>Reach out at Help-QA.com to get personalized solutions to your problems and share your worldly insight with those that need your help.</p>
        <hr>
      </div>
      <div class="tags">
        Tags:
        <%= tags_container(@global_tags, min: 12, max: 12) %>,
        <a href="<%= tags_path %>" class="underline">all tags</a>, or just jump to a tag:
        <%= form_tag redirect_tags_path do %>
          <div class="tag-search">
            <div class="btn-wrapper">
              <button type="button" name="button">Goto Tag</button>
            </div>
            <div class="field-wrapper">
              <input type="text" name="tag_name">
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <% if @currently_popular_post %>
      <% post = @currently_popular_post %>
      <div class="popular-post">
        <h6>Currently Popular Post</h6>
        <a href="<%= post_path(post) %>" class="post">
          <%= avatar(post.avatar(size: 30), size: 30) %>
          <div class="words">
            <div class="title"><%= markdown(with: [:ignore_previews], except: [:tags, :quote, :codeblock]) { post.title } %></div>
            <div class="details">
              <strong>- <%= pluralize_with_delimiter(post.reply_count, "reply") %></strong> to <%= post.username %><%= "##{post.author_id}" if can?(:view_anonymous_user) && post.posted_anonymously? %> @ <%= post.created_at.to_formatted_s(:short_with_time) %>
            </div>
          </div>
        </a>
      </div>
    <% end %>
    <% if user_signed_in? %>
      <div class="recent-members">
        <h6>Most Recent Friends Online</h6>
        <div class="members">
          <% @recent_friends.each do |user| %>
            <%
              last_online = if user.online?
                "is online!"
              elsif (user.last_seen_at || user.created_at) > 30.days.ago
                "last online: #{timeago(user.last_seen_at)}"
              else
                "last online: #{(user.last_seen_at || user.created_at).to_formatted_s(:short_with_time)}"
              end
            %>
            <%= avatar(user.avatar(size: 60), { href: user_path(user), size: 60, status: user.online? ? 'online' : 'offline', tooltip: { name: user.username, timestamp: last_online } }) %>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="recent-members">
      <h6>Most Recent Members Online</h6>
      <div class="members">
        <% @recent_members.each do |user| %>
          <%
            last_online = if user.online?
              "is online!"
            elsif (user.last_seen_at || user.created_at) > 30.days.ago
              "last online: #{timeago(user.last_seen_at)}"
            else
              "last online: #{(user.last_seen_at || user.created_at).to_formatted_s(:short_with_time)}"
            end
          %>
          <%= avatar(user.avatar(size: 60), { href: user_path(user), size: 60, status: user.online? ? 'online' : 'offline', tooltip: { name: user.username, timestamp: last_online } }) %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="posts-side">
    <div class="new-post-container">
      <%= form_for @post || Post.new do |f| %>
        <div class="text-area-wrapper">
          <%= render partial: "layouts/markdown_tools" %>
          <% should_show_default_text = params[:post_text].blank? || Post.text_matches_default_text?(params[:post_text]) %>
          <%= f.text_area :body, rows: 6, class: "autofillable-field #{'js-clear-text-after-focus' if should_show_default_text}", value: params[:post_text].presence || Post::DEFAULT_POST_TEXT.html_safe %>
        </div>
        <div class="post-controls">
          <% unless user_signed_in? %>
            <div class="input-wrapper">
              <label for="new-post-email">Email: </label>
              <input type="new-post-email" name="new_user[email]" value="<%= params.dig(:new_user, :email) %>">
            </div>
          <% end %>
          <div class="input-wrapper">
            <%= f.check_box :posted_anonymously, checked: params[:anonymous] == "1" || default_anonymous? %>
            <%= f.label :posted_anonymously, "Post Anonymously?" %>
          </div>
          <div class="input-wrapper"><%= f.submit "Post!" %></div>
          <% unless user_signed_in? %>
            <div class="small-text">
              Email address is required <br>
              You must be 13 years or older
            </div>
          <% end %>
        </div>
        <% unless user_signed_in? %>
          <div class="form-field">
            <%= label_tag :recaptcha, "" %>
            <!-- <div class="g-recaptcha" data-sitekey="<%= ENV['HELPQA_RECAPTCHA_KEY'] %>"></div> -->
            <div class="g-recaptcha" data-sitekey="6LfxY4UUAAAAAJhxucJRBhnboedChh2tZnb9Pc61"></div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="posts-wrapper">
      <h1>Most Recent Posts</h1>
      <div class="tags">
        Topics include:
        <% @current_tags.each do |tag| %>
          <a href="<%= tag_path(tag) %>" class="underline"><%= tag.tag_name %></a>,
        <% end %>
        and <a href="<%= tags_path %>" class="underline">much more</a>...
      </div>
      <div class="posts-container">
        <%= render partial: "posts/index", locals: { posts: @recent_posts } %>
      </div>
      <div class="history">
        <a href="<%= history_path %>" class="underline">View and Search All Posts</a>
      </div>
    </div>
  </div>
</div>