config/routes.rb
Rails.application.routes.draw do
  root to: 'index#index'

  get :form_redirect, controller: :application
  get :flash_message, controller: :application
  get :"terms-of-service", controller: :static_pages
  get :"privacy-policy", controller: :static_pages
  get :faq, controller: :static_pages
  get :donate, controller: :static_pages
  post :donate, controller: :static_pages, action: :one_time_donation
  get :emoji, controller: :static_pages
  get :chat, controller: :chat
  get :chat_list, controller: :chat
  get "chat/remove_message/:id" => "chat#remove_message", as: :remove_message
  get "chat/revoke_access/:id" => "chat#revoke_access", as: :revoke_access

  resource :feedback, path: "feedback", only: [:show, :create] do
    get ":id/edit", action: :edit, as: :edit
    post ":id/complete", action: :complete, as: :complete
    get :all, action: :index
    post :all, action: :redirect_all
  end

  devise_for :users, path: :account, path_names: { sign_in: "login", sign_out: "logout" }, controllers: {
    confirmations: "devise/user/confirmations",
    # omniauth_callbacks: "devise/user/omniauth_callbacks",
    passwords: "devise/user/passwords",
    registrations: "devise/user/registrations",
    sessions: "devise/user/sessions",
    unlocks: "devise/user/unlocks"
  }

  get "tags/:tags" => "tags#show", as: :tag
  resources :tags, only: [ :index ] do
    post :redirect, on: :collection
  end

  post "history" => "posts#history_redirect", as: :history_redirect
  get "history(((((/:claimed_status)/:reply_count)/:user_status)/:tags)/:page)" => "posts#history", as: :history

  get "url" => "replies#meta", as: :get_meta
  get "preview" => "replies#preview"
  get "posts/:id.csv" => "posts#show", format: :csv
  resources :posts, except: [ :destroy ] do
    member do
      get :vote
      get :subscribe
      post :mod
    end
    resources :replies, only: [ :create, :update ] do
      post :mod
      get :favorite
      get :unfavorite
    end
  end

  resources :replies, only: [ :index ] do
  end

  resource :mod, only: [:show] do
    get :queue, on: :member

    resource :bans, only: [:show] do
      resources :banned_users, path: :users
      resources :banned_ips, path: :ip
      resources :chat_bans, path: :chat
    end
    resources :audit, only: [ :index, :show ] do
      post :search, on: :collection
    end
  end

  resource :admin, only: [] do
    resources :email_blobs, path: :emails do
      post :search, on: :collection
    end
  end

  resource :account, only: [ :index, :edit, :update ] do
    get :confirm
    patch :confirm, action: :set_confirmation
    get :avatar
    post :avatar, action: :update_avatar
    get :notifications

    resources :subscriptions, only: [ :index ] do
      collection do
        post :subscribe
        delete :subscribe, action: :unsubscribe
      end
    end
    resources :friends, only: [ :index, :update, :destroy ]
    resources :profile, only: [ :index ] do
      post :update, on: :collection
    end
    resources :settings, only: [ :index ] do
      post :update, on: :collection
    end
    resources :notices, only: [ :index ] do
      post :mark_all_read, on: :collection
    end
    resources :invites, only: [ :index ] do
      post :mark_all_read, on: :collection
    end
  end

  post "update_user_search" => "users#update_user_search", as: :update_user_search
  resources :users, except: [ :destroy ] do
    member do
      put :add_friend
      put :remove_friend
      post :moderate
      get :spy
    end
    get "shoutbox" => "shouts#index", as: :shouts
    post "shoutbox" => "shouts#create"
    get "shout-trail/:other_user_id" => "shouts#shouttrail", as: :shouttrail
    resources :posts, only: [ :index ]
    resources :replies, only: [ :index ]
  end
  resources :shouts, only: [:show, :update, :destroy]

  resources :webhooks, only: [] do
    collection do
      post :email
    end
  end

  require 'sidekiq/web'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount ActionCable.server => '/cable'

end

app/models/feedback.rb
# == Schema Information
#
# Table name: feedbacks
#
#  id              :integer          not null, primary key
#  user_id         :integer
#  email           :string
#  body            :text
#  url             :string
#  completed_at    :datetime
#  completed_by_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Feedback < ApplicationRecord
  include UrlHelper
  belongs_to :user, optional: true
  belongs_to :completed_by, optional: true, class_name: "User"

  validate :message_exists
  validate :can_follow_up
  after_create :notify_slack
  after_commit :broadcast_creation

  scope :search_for,   ->(text) { where("feedbacks.body ILIKE ?", "%#{text.gsub(/['"’“”]/, "['\"’“”]")}%") }
  scope :regex_search, ->(text) { where("feedbacks.body ~* ?", text.gsub(/['"’“”]/, "['\"’“”]")) }
  scope :unresolved,   -> { where(completed_at: nil) }
  scope :resolved,     -> { where.not(completed_at: nil) }
  scope :by_username,  ->(username) { where.not(user_id: nil).joins(:user).where("users.username ILIKE ?", "%#{username}%") }

  def resolved?; completed_at?; end
  def unresolved?; !resolved?; end

  def display_name
    user.try(:username) || email
  end

  def resolve(user)
    update(completed_by: user, completed_at: DateTime.current)
  end

  private

  def broadcast_creation
    mod_message = unresolved? ? "<a href=\"/mod/queue\">There is a new reply that requires approval.</a>" : ""
    User.mod.each do |mod|
      ActionCable.server.broadcast("notifications_#{mod.id}", message: mod_message)
    end
  end

  def notify_slack
    slack_message = "New Feedback from #{display_name}"
    link_url = url_for(Rails.application.routes.url_helpers.edit_feedback_path(id))
    attachment = {
      fallback: "#{body} - Ticket: ##{id}: #{link_url}",
      title: slack_message,
      title_link: link_url,
      text: "#{body} - Ticket: ##{id}: #{link_url}",
      color: :good
    }
    SlackNotifier.notify("", attachments: [attachment])
  end

  def message_exists
    return unless body.blank?

    errors.add(:base, "Please leave a description (is as much detail as you can) about the problem or issue you are experiencing.")
  end

  def can_follow_up
    return if user.present? || (email.present? && email =~ Devise.email_regexp)

    errors.add(:email, "must be a valid email address.")
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :authenticate_mod, only: [:index, :edit, :complete]

  def redirect_all
    redirect_to all_feedback_path(params.permit(:search, :by_user, :resolution_status))
  end

  def index
    @feedbacks = Feedback.order(created_at: :desc, id: :desc).page(params[:page])
    @feedbacks = @feedbacks.resolved if params[:resolution_status].to_s.to_sym == :resolved
    @feedbacks = @feedbacks.unresolved if params[:resolution_status].to_s.to_sym == :unresolved
    @feedbacks = @feedbacks.search_for(params[:search]) if params[:search].present?
    @feedbacks = @feedbacks.by_username(params[:by_user]) if params[:by_user].present?
  end

  def show
    @feedback = Feedback.new
  end

  def edit
    @feedback = Feedback.find(params[:id])
  end

  def create
    @feedback = Feedback.new(feedback_params)
    @feedback.user = current_user if user_signed_in?

    if !recaptcha_success?
      flash.now[:alert] = "Please check the \"I'm not a robot\" checkbox to show that you are not a bot."
      render :show
    elsif @feedback.save
      redirect_to root_path, notice: "Thank you for your feedback. A moderator will review shortly, and if we need to follow up, we will get back to you in a timely manner."
    else
      flash.now[:alert] = "Failed to submit your Feedback. Please fix the problems listed below and try again."
      render :show
    end
  end

  def complete
    @feedback = Feedback.find(params[:id])
    @feedback.resolve(current_user)

    redirect_to edit_feedback_path(@feedback)
  end

  private

  def recaptcha_success?
    response = RestClient.post("https://www.google.com/recaptcha/api/siteverify", secret: ENV['HELPQA_RECAPTCHA_SECRET'], response: params["g-recaptcha-response"], remoteip: request.try(:remote_ip))
    JSON.parse(response)["success"]
  rescue TypeError => e
    false
  rescue JSON::ParserError => e
    false
  end

  def feedback_params
    params.require(:feedback).permit(
      :email,
      :body,
      :url
    )
  end

end

app/views/feedbacks/_index.html.erb
<% hide_tags ||= false %>

<% feedbacks.each do |feedback| %>
  <a href="<%= edit_feedback_path(feedback) %>" class="post-container">
    <div class="post-description">
      <div class="title">
        <small><%= feedback.body.squish.first(50) %></small>
      </div>
      <div class="post-information">
        by <strong><%= feedback.display_name %></strong> on <%= feedback.created_at.to_formatted_s(:short_with_time) %>
        <% if feedback.resolved? %>
          - Resolved by <%= feedback.completed_by.try(:username) %> on <%= feedback.completed_at.to_formatted_s(:simple_with_time) %>
        <% end %>
      </div>
    </div>
  </a>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Feedback from <%= @feedback.display_name %></h1>

<% if @feedback.user.present? %>
  <p>User Profile: <%= link_to @feedback.display_name, user_path(@feedback.user) %></p>
<% end %>

<% if @feedback.url.present? %>
  <p>Problem URL: <a href="<%= @feedback.url %>"><%= @feedback.url %></a></p>
<% end %>

<hr>

<pre style="white-space: pre-wrap;"><%= @feedback.body %></pre>

<% if @feedback.resolved? %>
  Resolved by <%= @feedback.completed_by.try(:username) %> on <%= @feedback.completed_at.to_formatted_s(:simple_with_time) %>
<% else %>
  <%= button_to "Mark as Resolved", complete_feedback_path, method: :post %>
<% end %>

app/views/feedbacks/feedback.html.erb
<% content_for(:title) { "Feedback" } %>

<h1>File a Report</h1>

<div class="stretch-children">
  <%= form_for @feedback, url: feedback_path do |f| %>
    <p>Have a question? Found a bug? Missing something? Found a post/reply that broke our TOS?</p>
    <p>Let us know about problems, bad users, broken pages, offensive posts/replies, bugs, &amp; errors.</p>

    <%= errors(@feedback, title: "Failed to submit Feedback:") %>

    <% if user_signed_in? %>
      <p>While responding to a question, or if we need additional information, we will communicate through the email address you have on file: <br><strong><%= current_user.email %></strong></p>
    <% else %>
      <p>In case we need to follow up or respond to your question, please provide your email below:</p>
      <div class="form-field">
        <%= f.label :email, "Email:" %>
        <%= f.email_field :email, class: "full-width"  %>
      </div>
    <% end %>

    <div class="form-field">
      <%= f.label :body, "Why are you reporting this?" %>
      <%= f.text_area :body, rows: 10, class: "full-width" %>
    </div>

    <div class="form-field">
      <%= f.label :url do %>
      URL <small><i>(If this is a report concerning a post or user, please leave a link for us to investigate)</i></small>
      <% end %>
      <%= f.text_field :url, value: @feedback.url || params[:report_url], class: "full-width" %>
    </div>

    <div class="form-field">
      <br>
      <%= f.submit "Send it off" %>
    </div>
  <% end %>

  <div class="warning">
    <p>
      <strong>PLEASE NOTE:</strong> <br>
      Do NOT use this to reply to a post or ask for assistance, you will get no reply.
    </p>
    <p>
      This form is only for contacting admins about site problems or reporting users for breaking our TOS.
    </p>
  </div>
</div>

app/views/feedbacks/index.html.erb
<% total_feedbacks = @feedbacks.total_count || 0 %>
<% first_feedback = [(@feedbacks.limit_value * (@feedbacks.current_page - 1)) + 1, total_feedbacks, 0].sort[1] %>
<% last_feedback = [@feedbacks.limit_value * @feedbacks.current_page, total_feedbacks, 0].sort[1] %>
<% title = "#{pluralize_with_delimiter(total_feedbacks, 'messages')}, Messages #{number_with_delimiter(first_feedback)} to #{number_with_delimiter(last_feedback)}" %>
<% meta_title title %>
<h2><i>Feedback:</i> <%= title %></h2>

<div class="history-page">
  <%= form_tag url: all_feedback_path do %>
    <%= hidden_field_tag :resolution_status, params[:resolution_status] %>
    <%= hidden_field_tag :by_user, params[:by_user] %>
    <%= hidden_field_tag :search, params[:search] %>

    <div class="search-form">
      <h6>Search Text</h6>
      <input type="text" name="search" value="<%= params[:search] %>">
      <%= submit_tag "Search" %>

      <div class="filters">
        <h6>Filters</h6>
        <div class="filter">
          <div class="name">Resolution State:</div>
          <div class="links">
            <%= filter_feedback_link("Resolved", resolution_status: :resolved) %>,
            <%= filter_feedback_link("Unresolved", resolution_status: :unresolved) %>,
            <%= filter_feedback_link("Off", resolution_status: nil) %>
          </div>
        </div>
        <div class="filter reset-filters">
          <a href="<%= all_feedback_path %>" class="underline">Reset All Filters</a>
        </div>
      </div>

      <div class="by-user">
        <h6>Search By Username</h6>
        <input type="text" name="by_user" value="<%= params[:by_user] %>">
        <%= submit_tag "Search" %>
      </div>
    </div>
  <% end %>
  <div class="search-results">
    <% total_pages = 5 %>
    <% window_sizes = {
      default: (total_pages / 2).floor,
      low: total_pages - @feedbacks.current_page,
      high: total_pages - (@feedbacks.total_pages - @feedbacks.current_page) - 1
    } %>

    <%= feedback_pagination @feedbacks, window: window_sizes.values.max, outer_window: 1, params: {} %>
    <%= render partial: "index", locals: { feedbacks: @feedbacks } %>
    <%= feedback_pagination @feedbacks, window: window_sizes.values.max, outer_window: 1, params: {} %>
    <p></p>
  </div>
</div>

app/views/feedbacks/show.html.erb
<%= content_for(:head_scripts) do %>
  <script src="https://www.google.com/recaptcha/api.js"></script>
<% end %>

<% meta_title "Feedback" %>

<h1>File a Report</h1>

<div class="feedback-wrapper">
  <div class="warning">
    <p>
      <strong>PLEASE NOTE:</strong> <br>
      Do NOT use this to reply to a post or ask for assistance, you will get no reply.
    </p>
    <p>
      This form is only for contacting admins about site problems or reporting users for breaking our TOS.
    </p>
  </div>

  <%= form_for @feedback, url: feedback_path do |f| %>
    <p>Have a question? Found a bug? Missing something? Found a post/reply that broke our TOS?</p>
    <p>Let us know about problems, bad users, broken pages, offensive posts/replies, bugs, &amp; errors.</p>

    <%= errors(@feedback, title: "Failed to submit Feedback:") %>

    <% if user_signed_in? %>
      <p>While responding to a question, or if we need additional information, we will communicate through the email address you have on file: <br><strong><%= current_user.email %></strong></p>
    <% else %>
      <p>In case we need to follow up or respond to your question, please provide your email below:</p>
      <div class="form-field">
        <%= f.label :email, "Email:" %>
        <%= f.email_field :email, class: "full-width" %>
      </div>
    <% end %>

    <div class="form-field">
      <%= f.label :body, "Why are you reporting this?" %>
      <%= f.text_area :body, rows: 8, class: "full-width" %>
    </div>

    <div class="form-field">
      <%= f.label :url do %>
        URL <small><i>(If this is a report concerning a post or user, please leave a link for us to investigate)</i></small>
      <% end %>
      <%= f.text_field :url, value: @feedback.url || params[:report_url], class: "full-width" %>
    </div>

    <div class="form-field">
      <%= label_tag :recaptcha, "Spam check" %>
      <!-- <div class="g-recaptcha" data-sitekey="<%= ENV['HELPQA_RECAPTCHA_KEY'] %>"></div> -->
      <div class="g-recaptcha" data-sitekey="6LfxY4UUAAAAAJhxucJRBhnboedChh2tZnb9Pc61"></div>
    </div>

    <div class="form-field">
      <br>
      <%= f.submit "Send it off" %>
    </div>
  <% end %>
</div>